# Generated by Django 3.1.7 on 2021-05-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210507_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='submit_date'),
        ),
    ]
