# Generated by Django 3.1.7 on 2021-07-10 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_auto_20210507_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='name',
        ),
        migrations.AddField(
            model_name='organiser',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
