# Generated by Django 3.1.7 on 2021-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210710_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='contact',
            field=models.CharField(default=9876543210, max_length=14),
            preserve_default=False,
        ),
    ]
