# Generated by Django 3.1.7 on 2021-07-14 15:03

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_organiser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='github_link',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_github',
            field=models.BooleanField(default=False, verbose_name='If you want the participant to provide a GitHub link please select this'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=course.models.upload_location_submission),
        ),
    ]
