# Generated by Django 3.1.7 on 2021-07-15 09:32

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210714_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=course.models.upload_location_submission),
        ),
        migrations.AlterField(
            model_name='submission',
            name='github_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
