# Generated by Django 3.1.7 on 2021-07-22 19:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=None),
        ),
    ]
