# Generated by Django 3.1.7 on 2021-07-24 07:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_auto_20210723_0044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('task', 'account')},
        ),
    ]
